# Site settings
title: Blog |
email: jiwan.cse@gmail.com
description: Blog
baseurl: /blog
url: "https://heartstchr.github.io"
name: tech-blog

#Build settings
markdown: redcarpet
highlighter: pygments
permalink: none

#Author settings
jiwan_ghosal:
    name: Jiwan Ghosal
    email: jiwan.cse@gmail.com
    web: https://heartstchr.github.io/
elaine_osbourn:
    name: Elaine Osbourn
    web: https://www.twitter.com/kittylainey