# Site settings
title: TechBlog
email: heartstchr@live.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
exclude: ['README.md']
baseurl: "/tech-blog" # the subpath of your site, e.g. /blog/
url: "http://heartstchr.github.com/tech-blog" # the base hostname & protocol for your site
twitter_username: stchr_ghosal
github_username:  heartstchr

# Build settings
markdown: redcarpet
